version: "3"

volumes:
    app.cache:

services:
  webserver:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    container_name: phpfpm
    image: nanoninja/php-fpm
    volumes:
      - ./app:/app
      - app.cache:/app/var
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.201.27"  #your host ip
      PHP_IDE_CONFIG: "serverName=docker"
      DATABASE_URL: pgsql://postgres:tiger@db:5432/postgres
    links:
      - db

  db:
    container_name: postgres
    build:
        context: config/postgresql
    environment:
      POSTGRES_PASS: "tiger"
    ports:
      - "5432:5432"
    volumes:
      - ./db_dump/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql/setconfig.sh:/docker-entrypoint-initdb.d/setconfig.sh
      #- ./config/postgresql/cron.sql:/docker-entrypoint-initdb.d/cron.sql
