version: "3"

volumes:
    app.cache:

services:
  webserver:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    container_name: phpfpm
    image: nanoninja/php-fpm
    volumes:
      - ./app:/app
      - app.cache:/app/var
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.201.27"
      PHP_IDE_CONFIG: "serverName=docker"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_DATABASE: postgres
      DB_USERNAME: scott
      DB_PASSWORD: tiger
      DATABASE_URL: pgsql://scott:tiger@postgres:5432/postgres
    links:
      - db

  composer:
    image: composer
    volumes:
      - ./app:/app
    command: "update"

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: scott
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"

